### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by rubenvdham** [cpitclaudel/monospacifier#24]
`$ fontforge -script monospacifier.py --input input/Raleway-* --references fonts/CourierStd.otf --copy-metrics`

```Copyright (c) 2000-2018 by George Williams. See AUTHORS for Contributors.
 License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
 with many parts BSD <http://fontforge.org/license.html>. Please read LICENSE.
 Based on sources from 13:38 UTC 25-Apr-2019-ML-D.
 Based on source from git with hash: f0c988e05b088411a47668c4582848165f5f0e4d
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
Warning: Mac and Windows entries in the 'name' table differ for the
  Fullname string in the language English (US)
  Mac String: Courier Std Medium
  Windows String: CourierStd
>>> For reference font Courier Std:
The following table(s) in the font have been ignored by FontForge
  Ignoring 'DSIG' digital signature table
>>> - Monospacifying Raleway Black
Traceback (most recent call last):
  File "monospacifier.py", line 308, in <module>
    main()
  File "monospacifier.py", line 294, in main
    args.copy_metrics, args.rename))
  File "monospacifier.py", line 283, in process_fonts
    path = make_monospace(reference, fallback, gscaler, save_to, copy_metrics, renames)
  File "monospacifier.py", line 207, in make_monospace
    cleanup_font_name(fallback.fontname, renames),
  File "monospacifier.py", line 201, in cleanup_font_name
    for old, new in renames:
TypeError: 'NoneType' object is not iterable
```

Running Arch Linux, Compiled Fontforge from source using the following workaround: https://stackoverflow.com/questions/29441053/importerror-psmat-is-not-a-built-in-module

**Comment by cpitclaudel** [comment]
Thanks! The script wasn't working without `--rename`.

Btw, you shouldn't need to use fontforge -script (if fontforge is properly compiled, psmat should be available system-wide).

**Comment by rubenvdham** [comment]
Ahaa! Thanks for the prompt fix. To get it to work I just needed to change unichr() to chr().

Somehow Python3 can't import psmat, and python2 can't import fontforge at all. Not entirely sure what's the issue.
